### ISSUE TITLE
Default FUZZYCD_MODE is inconsistent in readme

### ISSUE THREAD

**Issue by adamguos** [DannyBen/fuzzycd#16]
Hi, I noticed that the `Fuzzy search` section says interactive mode is the default:

> If more than one directories match, you will be prompted to choose one of the matching directories when running in interactive mode (default), or you will cd to the best match when running in non-interactive mode.

However the `Show Usage Pattern` section says non-interactive mode is the default:

>   FUZZYCD_MODE
    Set operation mode (one of: m, i, p)
      m = minimal, non interactive, always cd to best match (default)
      i = interactive when needed, no preview
      p = interactive when needed, with ls preview

Based on my setup process it looks like non-interactive is the correct default.

**Comment by DannyBen** [comment]
Thank you for pointing that out.

Originally, the interactive mode was the default, but with the latest release ([changelog](https://github.com/DannyBen/fuzzycd/blob/master/CHANGELOG.md#v023---2024-04-13)), I decided to make the non interactive mode the default - since I personally was using the non interactive mode exclusively from the get go, and figured people don't want to waste time in menus when CDing.

I will fix the README.
